### ISSUE TITLE
Threadsafe?

### ISSUE THREAD

**Issue by n-rodriguez** [robinst/taglib-ruby#76]
Hi! Is this lib threadsafe?

**Comment by robinst** [comment]
It doesn't add any thread-unsafety of its own on top of [taglib](http://taglib.org/). taglib itself doesn't document whether it's thread-safe.

I've found this: http://thread.gmane.org/gmane.comp.kde.devel.taglib/648

But the offending code has since been fixed: https://github.com/taglib/taglib/blob/a19a623d4bfaa7d26ece05ac73c4716e5710d34f/taglib/toolkit/trefcounter.cpp

So the best answer is currently "Maybe", sorry about that. I suggest you try it out and report issues if you find any.
